### ISSUE TITLE
Example notebook loading error

### ISSUE THREAD

**Issue by ToBlueSky** [stanford-futuredata/FrugalGPT#1]
When I open the [Google Colab Notebook](https://colab.research.google.com/drive/1LM-Wq-u87VI4TKM4thpnwepnOxTAtWaM?authuser=1#scrollTo=a95a1eec) Error occurred

![image](https://github.com/stanford-futuredata/FrugalGPT/assets/22974395/9834c7a9-1e61-4bc5-8145-bde77e99b514)

**Comment by lchen001** [comment]
Hi @ToBlueSky, 

I am happy to help! Though I was not able to reproduce the error locally: I successfully opened it in the Chrome incognito mode and also a few other browsers. 

<img width="761" alt="Open Colab locally" src="https://github.com/stanford-futuredata/FrugalGPT/assets/17239764/8e12d20e-d820-465b-831c-c50eb9957f33">

Could you provide more details on your local setup? That might help me identify the exact problem. Thanks!

**Comment by ToBlueSky** [comment]
Hi @lchen001 
Thanks for you reply, my env is ubuntu google, but now I can access it by windows edge or iPhone safari, although It also pop up error window in edge, but I can open it from google drive
